# Nearest Neigbhor mit Keras

von Eric Hirsch und Jonas Morsch 

###  Einbinder aller benötigten Bibliotheken 

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import random 

from sklearn.model_selection import train_test_split , KFold
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix,mean_squared_error
from collections import Counter

import Data_preparation as DV 
DV=DV.Data_preparation()


### laden der Daten

In [3]:

df=DV.load_csv_to_df("ricsData_big_v5.csv")
df=df[["Rel_BreitGross","RelSpitze_oben","RelSpitze_unten","Anzahl_Linie","Label"]]
train_features,test_features,train_labels,test_labels=DV.split_data(df,0.5)
df.head()

training set size: 402 samples 
test set size: 403 samples


Rel_BreitGross  RelSpitze_oben  RelSpitze_unten  Anzahl_Linie  Label
0        0.288606        0.074919         0.618893             6      0
1        0.494050        0.685185         0.634259             5      0
2        0.497540        0.986384         0.989410            15      0
3        0.480687        0.714286         0.592262            21      0
4        0.322937        0.159763         0.633136            21      0

### Daten Normalisiern 


In [4]:
scaler= Normalizer().fit(train_features) 
normalized_x_train= scaler.transform(train_features) 
normalized_x_test= scaler.transform(test_features) 
print('x train before Normalization')
print(train_features[0:1])
print('\nx train after Normalization')
print(normalized_x_train[0:1])

x train before Normalization
     Rel_BreitGross  RelSpitze_oben  RelSpitze_unten  Anzahl_Linie
569         0.67762        0.605701          0.16152             1

x train after Normalization
[[0.49790937 0.44506379 0.11868368 0.73479158]]


### Erstellen und trainiern eines K nearest Neigbhour Klassifiers 

In [5]:
K=6
knn=KNeighborsClassifier(K)
knn.fit(normalized_x_train, np.ravel(train_labels))
y_pred= knn.predict(normalized_x_test)
#print(y_pred)

### Ausgeben der Metrics

In [7]:
print(f'The accuracy of sklearn implementation is {accuracy_score(np.ravel(test_labels), y_pred)}')
print(confusion_matrix(test_labels, y_pred))
print(classification_report(test_labels, y_pred))


rms=mean_squared_error(test_labels,y_pred,squared=False)

print("Mean squarred Error:",rms)



The accuracy of sklearn implementation is 0.5037220843672456
[[66 30 23]
 [37 89 21]
 [59 30 48]]
              precision    recall  f1-score   support

           0       0.41      0.55      0.47       119
           1       0.60      0.61      0.60       147
           2       0.52      0.35      0.42       137

    accuracy                           0.50       403
   macro avg       0.51      0.50      0.50       403
weighted avg       0.52      0.50      0.50       403

Mean squarred Error: 1.051997980920611


### Ein einzelnes Bild vorhersagen 

In [8]:
random_index=random.randint(0,len(test_features))
prediction=knn.predict(test_features.values[random_index].reshape(1,-1))
print("Class predictet by KNN: {}".format(prediction))
print("actual Class: {} ".format(test_labels.iloc[random_index,:]))

Class predictet by KNN: [1]
actual Class: Label    0
Name: 54, dtype: int64 
