# Nearest Neigbhor

In [64]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import random 

from sklearn.model_selection import train_test_split , KFold
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from collections import Counter

import Data_preparation as DV 
DV=DV.Data_preparation()


### Load the Dataset 

In [75]:

df=DV.load_csv_to_df("ricsData_big_v5.csv")
train_features,test_features,train_labels,test_labels=DV.split_data(df,0.5)


training set size: 402 samples 
test set size: 403 samples


### Normalize the Dataset 


In [76]:
scaler= Normalizer().fit(train_features) # the scaler is fitted to the training set
normalized_x_train= scaler.transform(train_features) # the scaler is applied to the training set
normalized_x_test= scaler.transform(test_features) # the scaler is applied to the test set
print('x train before Normalization')
print(train_features[0:1])
print('\nx train after Normalization')
print(normalized_x_train[0:1])

x train before Normalization
     Rel_BreitGross  RelSpitze_oben  RelSpitze_unten  Anzahl_Linie  \
124        0.400092        0.116242         0.542994            55   

     Anzahl_Ecken  Anzahl_Kreis  innere_Konturen  
124             3             0         0.090544  

x train after Normalization
[[0.00726304 0.00211019 0.00985718 0.99843729 0.05446022 0.
  0.00164368]]


### Make a KNN classifier

In [77]:
K=6
knn=KNeighborsClassifier(K)
knn.fit(normalized_x_train, np.ravel(train_labels))
y_pred= knn.predict(normalized_x_test)
#print(y_pred)

In [78]:
print(f'The accuracy of sklearn implementation is {accuracy_score(np.ravel(test_labels), y_pred)}')
print(confusion_matrix(test_labels, y_pred))
print(classification_report(test_labels, y_pred))


The accuracy of sklearn implementation is 0.5136476426799007
[[62 20 49]
 [39 66 38]
 [35 15 79]]
              precision    recall  f1-score   support

           0       0.46      0.47      0.46       131
           1       0.65      0.46      0.54       143
           2       0.48      0.61      0.54       129

    accuracy                           0.51       403
   macro avg       0.53      0.52      0.51       403
weighted avg       0.53      0.51      0.51       403



### Predict a single Image 

In [74]:
random_index=random.randint(0,len(test_features))
prediction=knn.predict(test_features.values[random_index].reshape(1,-1))
print("Class predictet by KNN: {}".format(prediction))
print("actual Class: {} ".format(test_labels.iloc[random_index,:]))

Class predictet by KNN: [0]
actual Class: Label    2
Name: 724, dtype: int64 
